version: "3"

### Creates a named network with the default bridge driver
# The network is shared between restheart and mongodb only
# See: https://docs.docker.com/engine/userguide/networking/dockernetworks/
# See: https://docs.docker.com/engine/reference/commandline/network_create/
networks:
   restheart-backend:

### Create a permanent, named data volume
# This makes much easier to identify where the mongodb data is stored on host
# See: https://docs.docker.com/engine/userguide/containers/dockervolumes/#mount-a-shared-storage-volume-as-a-data-volume
volumes:
   restheart-mongo-volume:

services:
    restheart:
        image: softinstigate/restheart
        container_name: restheart
        environment:
            MONGO_URI: mongodb://restheart:R3ste4rt!@mongodb
        command: ["--envFile", "/opt/restheart/etc/default.properties"]
        depends_on:
            - mongodb
        networks:
            - restheart-backend
        ports:
            - "8081:8081"

    mongodb:
        image: mongo:4.2
        container_name: restheart-mongo
        command: --bind_ip_all --auth
        environment:
            MONGO_INITDB_ROOT_USERNAME: restheart
            MONGO_INITDB_ROOT_PASSWORD: R3ste4rt!
        volumes:
            - restheart-mongo-volume:/data/db
        networks:
            - restheart-backend
